### ISSUE TITLE
Is there a way to use nested html elements in place of the 'content' property

### ISSUE THREAD

**Issue by darkchocobo82** [dfernandeza/pictip#5]
First off, this is a fantastic plugin! I would like to use it though for custom html elements in .Net if possible

Here's my question: Currently I am using the content property of pictip to load the html markup. Is it possible instead to pull all nested DOM elements by specifying the tooltipid without having to enter anything into the 'content' portion?

So essentially instead of passing the html markup through the content section, just passing the div or another compatible DOM element and having it load in all of the associated child DOM objects?

When using the 'content' property as shown below it works just fine but if i leave it out or set it to an empty string, I get back nothing as shown in the image example below
## EXAMPLE

I have some basic html markup using your script plugin:

```
<%-- image with spot positioned correctly on it --%>
<div id="map1">
    <div><img src="images/maps/map1.png" /></div>
</div>

<%-- tooltip container--%>
<div id="test">
    <h2>Map 1</h2>
    <p>Pulled from the actual div itself</p>
</div>
```

Here's the actual script:

```
var contents = {
    map1: [
                '<h2>Map 1</h2>',
                '<p>pulled from the contents object</p>
    ].join('')
};

$('#map1').pictip({
    spots: [
        { top: '180px', left: '370px', content: '', tooltipId: 'test', tooltipPosition: 'bl' }
    ],
    show: function (tooltip) {
        tooltip.addClass('is-open');
    },
    close: function (tooltip) {
        tooltip.removeClass('is-open');
    }
});
```

Example image showing the missing content:
![tmp](https://cloud.githubusercontent.com/assets/12213167/7557671/5ee9c6e4-f75b-11e4-92bc-69d16e7e8f57.png)

What I want to do is to have it display the stuff inside of
<div id="test"....
when the spot gets clicked. Is this currently possible?

**Comment by dfernandeza** [comment]
Hello, 

Thanks a lot for using my plugin. I created [this fiddle](http://jsfiddle.net/z93cnvoj/ ) so you can see how to use a jQuery selector to get the html content from a DOM element and use that content as the content of your Pictip tooltip.

Please, let me know if that works for you.
Regards

**Comment by darkchocobo82** [comment]
Thanks Daniel. This worked like a charm and I'm sure it will help others
having the same problem. Keep up the great work
